### ISSUE TITLE
[Question] Proper Settings To Train Wan T2V LoRA

### ISSUE THREAD

**Issue by ImNoobPleaseBeKind** [tdrussell/diffusion-pipe#116]
Hello, thank you for all your hard work and this amazing project.

I have successfully trained Wan T2V LoRA with this project, but it seems that my LoRA is not working properly when inferencing.
Can you please see if my setting is wrong?

```toml
output_dir = "/My-Wan-T2V-1.3B-Lora-V1"
dataset = "/dataset/dataset.toml"
epochs = 50
micro_batch_size_per_gpu = 1
pipeline_stages = 1
gradient_accumulation_steps = 4
gradient_clipping = 1.0
warmup_steps = 50
eval_every_n_epochs = 1
eval_before_first_step = true
eval_micro_batch_size_per_gpu = 1
eval_gradient_accumulation_steps = 1
save_every_n_epochs = 10
checkpoint_every_n_minutes = 30
activation_checkpointing = true
partition_method = "parameters"
save_dtype = "bfloat16"
caching_batch_size = 1
steps_per_print = 1
video_clip_mode = "single_middle"

[model]
type = "wan"
ckpt_path = "/wan/Wan2.1-T2V-1.3B"
dtype = "bfloat16"
transformer_dtype = "float8"
timestep_sample_method = "logit_normal"

[adapter]
type = "lora"
rank = 64
dtype = "bfloat16"

[optimizer]
type = "adamw_optimi"
lr = 2e-5
betas = [ 0.9, 0.99,]
weight_decay = 0.02
eps = 1e-8
```

I have successfully trained the character LoRA with this config as a total of 50 epochs with 300 steps,
But when I try to inference, LoRA does not work. 
Can you please tell me if I'm missing something?
