### ISSUE TITLE
Breaking change in last 1-2 days (`KeyError: 'enable_wandb'`)

### ISSUE THREAD

**Issue by entmike** [tdrussell/diffusion-pipe#75]
Just a heads up, people with existing configs may get an error.  I had to ensure I had the following new entries in my config toml that were not required previously:

```toml
[monitoring]
enable_wandb = false
```

Maybe this helps someone else!
